#ifndef __PX_GPIO_INIT_STM32L072RB_H__
#define __PX_GPIO_INIT_STM32L072RB_H__
/* =============================================================================
     ____    ___    ____    ___    _   _    ___    __  __   ___  __  __ TM
    |  _ \  |_ _|  / ___|  / _ \  | \ | |  / _ \  |  \/  | |_ _| \ \/ /
    | |_) |  | |  | |     | | | | |  \| | | | | | | |\/| |  | |   \  /
    |  __/   | |  | |___  | |_| | | |\  | | |_| | | |  | |  | |   /  \
    |_|     |___|  \____|  \___/  |_| \_|  \___/  |_|  |_| |___| /_/\_\

    Copyright (c) 2019 Pieter Conradie <https://piconomix.com>
 
    License: MIT
    https://github.com/piconomix/piconomix-fwlib/blob/master/LICENSE.md
    
    Title:          px_gpio_init_stm32l072rb.h : GPIO map to register init values
    Author(s):      Pieter Conradie
    Creation Date:  2019-06-08

============================================================================= */

/* _____STANDARD INCLUDES____________________________________________________ */

/* _____PROJECT INCLUDES_____________________________________________________ */
#include "px_defines.h"
#include "px_gpio.h"

#ifdef __cplusplus
extern "C" {
#endif
/* _____DEFINITIONS__________________________________________________________ */
// Port A defaults
#ifndef PX_GPIO_A0
#define PX_GPIO_A0 PX_GPIO(A, 0,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A1
#define PX_GPIO_A1 PX_GPIO(A, 1,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A2
#define PX_GPIO_A2 PX_GPIO(A, 2,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A3
#define PX_GPIO_A3 PX_GPIO(A, 3,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A4
#define PX_GPIO_A4 PX_GPIO(A, 4,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A5
#define PX_GPIO_A5 PX_GPIO(A, 5,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A6
#define PX_GPIO_A6 PX_GPIO(A, 6,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A7
#define PX_GPIO_A7 PX_GPIO(A, 7,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A8
#define PX_GPIO_A8 PX_GPIO(A, 8,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A9
#define PX_GPIO_A9 PX_GPIO(A, 9,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A10
#define PX_GPIO_A10 PX_GPIO(A, 10, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A11
#define PX_GPIO_A11 PX_GPIO(A, 11, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A12
#define PX_GPIO_A12 PX_GPIO(A, 12, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A13
#define PX_GPIO_A13 PX_GPIO(A, 13, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A14
#define PX_GPIO_A14 PX_GPIO(A, 14, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_A15
#define PX_GPIO_A15 PX_GPIO(A, 15, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
// Port B defaults
#ifndef PX_GPIO_B0
#define PX_GPIO_B0 PX_GPIO(B, 0,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B1
#define PX_GPIO_B1 PX_GPIO(B, 1,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B2
#define PX_GPIO_B2 PX_GPIO(B, 2,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B3
#define PX_GPIO_B3 PX_GPIO(B, 3,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B4
#define PX_GPIO_B4 PX_GPIO(B, 4,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B5
#define PX_GPIO_B5 PX_GPIO(B, 5,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B6
#define PX_GPIO_B6 PX_GPIO(B, 6,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B7
#define PX_GPIO_B7 PX_GPIO(B, 7,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B8
#define PX_GPIO_B8 PX_GPIO(B, 8,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B9
#define PX_GPIO_B9 PX_GPIO(B, 9,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B10
#define PX_GPIO_B10 PX_GPIO(B, 10, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B11
#define PX_GPIO_B11 PX_GPIO(B, 11, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B12
#define PX_GPIO_B12 PX_GPIO(B, 12, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B13
#define PX_GPIO_B13 PX_GPIO(B, 13, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B14
#define PX_GPIO_B14 PX_GPIO(B, 14, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_B15
#define PX_GPIO_B15 PX_GPIO(B, 15, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
// Port C defaults
#ifndef PX_GPIO_C0
#define PX_GPIO_C0 PX_GPIO(C, 0,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C1
#define PX_GPIO_C1 PX_GPIO(C, 1,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C2
#define PX_GPIO_C2 PX_GPIO(C, 2,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C3
#define PX_GPIO_C3 PX_GPIO(C, 3,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C4
#define PX_GPIO_C4 PX_GPIO(C, 4,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C5
#define PX_GPIO_C5 PX_GPIO(C, 5,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C6
#define PX_GPIO_C6 PX_GPIO(C, 6,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C7
#define PX_GPIO_C7 PX_GPIO(C, 7,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C8
#define PX_GPIO_C8 PX_GPIO(C, 8,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C9
#define PX_GPIO_C9 PX_GPIO(C, 9,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C10
#define PX_GPIO_C10 PX_GPIO(C, 10, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C11
#define PX_GPIO_C11 PX_GPIO(C, 11, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C12
#define PX_GPIO_C12 PX_GPIO(C, 12, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C13
#define PX_GPIO_C13 PX_GPIO(C, 13, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C14
#define PX_GPIO_C14 PX_GPIO(C, 14, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_C15
#define PX_GPIO_C15 PX_GPIO(C, 15, PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
// Port D defaults
#ifndef PX_GPIO_D2
#define PX_GPIO_D2 PX_GPIO(D, 2,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
// Port H defaults
#ifndef PX_GPIO_H0
#define PX_GPIO_H0 PX_GPIO(H, 0,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif
#ifndef PX_GPIO_H1
#define PX_GPIO_H1 PX_GPIO(H, 1,   PX_GPIO_MODE_ANA, PX_GPIO_OTYPE_NA, PX_GPIO_OSPEED_NA, PX_GPIO_PULL_NO, PX_GPIO_OUT_INIT_NA, PX_GPIO_AF_NA)
#endif

// Mode init values
#define GPIOA_MODER_VAL \
      PX_GPIO_REG_MODER_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A7)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_A15)

#define GPIOB_MODER_VAL \
      PX_GPIO_REG_MODER_INIT(PX_GPIO_B0)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B1)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B2)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B3)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B4)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B5)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B6)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B7)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B8)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B9)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_B15)

#define GPIOC_MODER_VAL \
      PX_GPIO_REG_MODER_INIT(PX_GPIO_C0)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C1)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C2)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C3)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C4)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C5)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C6)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C7)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_C15)

#define GPIOD_MODER_VAL \
      PX_GPIO_REG_MODER_INIT(PX_GPIO_D2)

#define GPIOH_MODER_VAL \
      PX_GPIO_REG_MODER_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_MODER_INIT(PX_GPIO_H1)

// Output type init values
#define GPIOA_OTYPER_VAL \
      PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A7)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_A15)

#define GPIOB_OTYPER_VAL \
      PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B0)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B1)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B2)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B3)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B4)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B5)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B6)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B7)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B8)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B9)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_B15)

#define GPIOC_OTYPER_VAL \
      PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C0)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C1)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C2)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C3)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C4)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C5)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C6)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C7)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_C15)

#define GPIOD_OTYPER_VAL \
      PX_GPIO_REG_OTYPER_INIT(PX_GPIO_D2)

#define GPIOH_OTYPER_VAL \
      PX_GPIO_REG_OTYPER_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_OTYPER_INIT(PX_GPIO_H1)

// Output speed init values
#define GPIOA_OSPEEDR_VAL \
      PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A7)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_A15)

#define GPIOB_OSPEEDR_VAL \
      PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B0)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B1)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B2)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B3)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B4)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B5)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B6)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B7)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B8)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B9)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_B15)

#define GPIOC_OSPEEDR_VAL \
      PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C0)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C1)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C2)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C3)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C4)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C5)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C6)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C7)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_C15)

#define GPIOD_OSPEEDR_VAL \
      PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_D2)

#define GPIOH_OSPEEDR_VAL \
      PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_OSPEEDR_INIT(PX_GPIO_H1)

// Pull up / pull-down register init values
#define GPIOA_PUPDR_VAL \
      PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A7)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_A15)

#define GPIOB_PUPDR_VAL \
      PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B0)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B1)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B2)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B3)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B4)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B5)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B6)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B7)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B8)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B9)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_B15)

#define GPIOC_PUPDR_VAL \
      PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C0)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C1)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C2)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C3)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C4)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C5)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C6)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C7)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_C15)

#define GPIOD_PUPDR_VAL \
      PX_GPIO_REG_PUPDR_INIT(PX_GPIO_D2)

#define GPIOH_PUPDR_VAL \
      PX_GPIO_REG_PUPDR_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_PUPDR_INIT(PX_GPIO_H1)

// Output data register init values
#define GPIOA_ODR_VAL \
      PX_GPIO_REG_ODR_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A7)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_A15)

#define GPIOB_ODR_VAL \
      PX_GPIO_REG_ODR_INIT(PX_GPIO_B0)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B1)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B2)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B3)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B4)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B5)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B6)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B7)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B8)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B9)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_B15)

#define GPIOC_ODR_VAL \
      PX_GPIO_REG_ODR_INIT(PX_GPIO_C0)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C1)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C2)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C3)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C4)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C5)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C6)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C7)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_C15)

#define GPIOD_ODR_VAL \
      PX_GPIO_REG_ODR_INIT(PX_GPIO_D2)

#define GPIOH_ODR_VAL \
      PX_GPIO_REG_ODR_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_ODR_INIT(PX_GPIO_H1)

// Alternative function register init values
#define GPIOA_AFRL_VAL \
      PX_GPIO_REG_AFRL_INIT(PX_GPIO_A0)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A1)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A2)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A3)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A4)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A5)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A6)  \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_A7)  \

#define GPIOA_AFRH_VAL \
      PX_GPIO_REG_AFRH_INIT(PX_GPIO_A8)  \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A9)  \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A10) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A11) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A12) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A13) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A14) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_A15)

#define GPIOB_AFRL_VAL \
      PX_GPIO_REG_AFRL_INIT(PX_GPIO_B0) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B1) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B2) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B3) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B4) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B5) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B6) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_B7) \

#define GPIOB_AFRH_VAL \
      PX_GPIO_REG_AFRH_INIT(PX_GPIO_B8) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B9) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B10) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B11) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B12) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B13) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B14) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_B15)

#define GPIOC_AFRL_VAL \
      PX_GPIO_REG_AFRL_INIT(PX_GPIO_C0) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C1) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C2) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C3) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C4) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C5) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C6) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_C7) \

#define GPIOC_AFRH_VAL \
      PX_GPIO_REG_AFRH_INIT(PX_GPIO_C8)  \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C9)  \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C10) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C11) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C12) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C13) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C14) \
    + PX_GPIO_REG_AFRH_INIT(PX_GPIO_C15)

#define GPIOD_AFRL_VAL \
      PX_GPIO_REG_AFRL_INIT(PX_GPIO_D2)

#define GPIOH_AFRL_VAL \
      PX_GPIO_REG_AFRL_INIT(PX_GPIO_H0) \
    + PX_GPIO_REG_AFRL_INIT(PX_GPIO_H1)

static const px_gpio_port_init_t px_gpio_port_a_init =
{
    GPIOA,
    GPIOA_MODER_VAL, 
    GPIOA_OTYPER_VAL, 
    GPIOA_OSPEEDR_VAL, 
    GPIOA_PUPDR_VAL, 
    GPIOA_ODR_VAL, 
    GPIOA_AFRL_VAL, 
    GPIOA_AFRH_VAL
};

static const px_gpio_port_init_t px_gpio_port_b_init =
{
    GPIOB,
    GPIOB_MODER_VAL, 
    GPIOB_OTYPER_VAL, 
    GPIOB_OSPEEDR_VAL, 
    GPIOB_PUPDR_VAL, 
    GPIOB_ODR_VAL, 
    GPIOB_AFRL_VAL, 
    GPIOB_AFRH_VAL
};

static const px_gpio_port_init_t px_gpio_port_c_init =
{
    GPIOC,
    GPIOC_MODER_VAL, 
    GPIOC_OTYPER_VAL, 
    GPIOC_OSPEEDR_VAL, 
    GPIOC_PUPDR_VAL, 
    GPIOC_ODR_VAL, 
    GPIOC_AFRL_VAL, 
    GPIOC_AFRH_VAL
};

static const px_gpio_port_init_t px_gpio_port_d_init =
{
    GPIOD,
    GPIOD_MODER_VAL, 
    GPIOD_OTYPER_VAL, 
    GPIOD_OSPEEDR_VAL, 
    GPIOD_PUPDR_VAL, 
    GPIOD_ODR_VAL, 
    GPIOD_AFRL_VAL, 
    0
};

static const px_gpio_port_init_t px_gpio_port_h_init =
{
    GPIOH,
    GPIOH_MODER_VAL, 
    GPIOH_OTYPER_VAL, 
    GPIOH_OSPEEDR_VAL, 
    GPIOH_PUPDR_VAL, 
    GPIOH_ODR_VAL, 
    GPIOH_AFRL_VAL, 
    0
};

#ifdef __cplusplus
}
#endif

#endif // #ifndef __PX_GPIO_INIT_STM32L072RB_H__
